### ISSUE TITLE
checklist for workshop (online)

### ISSUE THREAD

**Issue by nehamoopen** [UtrechtUniversity/workshop-introduction-to-R-and-data#28]
## Before 

- [ ] finalize workshop date(s)
- [ ] recruit instructors & helpers 
- [ ] contact communications to create an event page & registration form (at least 2 months before the workshop date)
- [ ] set up Teams channel & schedule Teams call
- [ ] email participants with setup & installation instructions + MS Teams details (at least 1 week before the workshop date) [link to email template]

## During 

- [ ] set up the status chart before the workshop starts
- [ ] promote the walk-in hours, programming cafe, other workshops, newsletter at the end of the workshop
- [ ] clear the status chart after the workshop ends

## After

- [ ] email participants post-workshop survey, course materials, details of other activities + newsletter [link to email template]
- [ ] generate and email certificates [link to script]
