### ISSUE TITLE
Feedback: Base R (Morning Session)

### ISSUE THREAD

**Issue by nehamoopen** [UtrechtUniversity/workshop-introduction-to-R-and-data#30]
Please leave your feedback for the Base R component (morning session) in this issue, thaaaanks!

**Comment by nehamoopen** [comment]
- [ ] Check Christine's feedback about the `help` function (issue #29)

**Comment by DorienHuijser** [comment]
Hello! I have not had time to go through the entire course (and I will not have time because of my holiday tomorrow), but I will paste what I had already written down, do with it what you want :)

- [ ] [Slide 93](https://utrechtuniversity.github.io/workshop-introduction-to-R-and-data/slides/slides_introduction.html#93): it says "{} Defining content of loops, functions", etc. > but this hasn’t been learned by then. Perhaps confusing?
- [ ] Exercise 7 [slide 104](https://utrechtuniversity.github.io/workshop-introduction-to-R-and-data/slides/slides_introduction.html#104): have participants already learned the %% modulo? I would not have known that function without learning it explicitly
- [ ] [Slide 119](https://utrechtuniversity.github.io/workshop-introduction-to-R-and-data/slides/slides_introduction.html#119): Input is an iterable object > too complicated. Suggestion: "input for a for-loop is an object with multiple (similar) elements. For example: a vector, a row or column in a dataframe, etc."
- [ ] [Slide 121](https://utrechtuniversity.github.io/workshop-introduction-to-R-and-data/slides/slides_introduction.html#121): I would prefer to not teach to use `i` in a for loop because it is so meaningless. Suggestion: `for{number in 1:6}`

**Comment by nehamoopen** [comment]
Note from @Mish-JPFD: the example function that participants create may not be super convenient because it's dependent on previously created vectors etc. It's way too specific and prone to error, it could be more general.

**Comment by nehamoopen** [comment]
- [ ] Overall, the introduction could be made more efficient (time-wise). Those who have been teaching the workshop for a while know how to skim through the introduction slides, but it's not helpful for those who're picking this up at the moment.

- [ ] Dataframes could be introduced before lists.

**Comment by nehamoopen** [comment]
- [ ] instead of simply leaving the modulo operator as a hint in the text, we could pre-fill the code block to include the modulo in advance AND/OR perhaps introduce + explain the modulo before they start

**Comment by StefanoRapisarda** [comment]
Some suggestions in case of a reorganization of the all material:
- The afternoon session is all about (tidyverse) functions. Perhaps a bitter more time can be dedicated to functions in the morning session, spending more words on the general concept and on parameters, also mentioning some functions to (later) be seen in the afternoon (like mean, sd, n);
- Currently the afternoon session follows the structure of the videos, maybe it can be reorganised in a single stream of data analysis, trying to introduce only one function at each step of the data analysis workflow. So for example (step by step), reading (readr), cleaning (select + conditional statement), re-arranging (mutate), selecting (select + more features), computing some statistics (group_by + stat functions), and visualising data. The all flow can be introduced at the very beginning of the afternoon session, so that people would know "where we are going";
- The afternoon session is all about functions, how about creating specific cheatsheets summarising all the functions used in the afternoon?
- Pipelines should be introduced at the very beginning of the afternoon session;
- Try to use at least one loop in the afternoon session? In this way all the subjects introduced in morning will be also used in the afternoon;
- Real life example and/or more context to the morning subjects. For people absolutely new to programming is hard to make sense of the programming concepts presented in the morning. It would be nice to use some examples to put them on context, or even refer very briefly to what will be done in the afternoon. For loop and conditional statements, for example, it could be showed how these could be used to "scan" all the rows of a dataframe to look for a specific value. For the functions, we could show a list of the most common functions, what they need, what they do. A small group of statistical functions could be a good idea, the same that will be used in the afternoon;
- This has been said here and there in the previous points, but just create more synergy between the morning and the afternoon material;
- All the cheatsheets links, or their pdf, or our custom cheatsheets should be in the course material

**Comment by DorienHuijser** [comment]
- [ ] baseR_exercises.Rmd exercise 6: "From your dataframe df, return the entries.." > Should become "From your dataframe df, return the rows ..." > Entries is confusing!
